---
- name: install default python3
  package:
    state: present
    name:
      - python3
      - python3-pip

- name: Fedora - install python39, python3-flake8
  package:
    state: present
    name:
      - python39
      - python3-flake8
  when: ansible_facts['distribution'] == "Fedora"

- name: RedHat 7 - install python-flake8
  package:
    state: present
    name: python-flake8
  when: >
    (ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat")
    and
    (ansible_facts['distribution_major_version'] == "7")

- name: RedHat 8 - install python3-flake8
  package:
    state: present
    name: python-flake8
  when: >
    (ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat")
    and
    (ansible_facts['distribution_major_version'] == "7")

- name: (Fedora) install/upgrade pipenv, poetry
  package:
    state: latest
    name:
      - pipenv
      - poetry
  when: ansible_facts['distribution'] == "Fedora"

- name: (CentOS/RedHat) install/upgrade pipenv, poetry (via pip)
  become: true
  become_user: "{{ ansible_env.USER }}"
  pip:
    executable: pip3
    state: latest
    extra_args: "--user"
    name:
      - pipenv
      - poetry
  when: (ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat")

- name: copy poetry Bash auto-completion script to /etc/bash_completion.d/
  copy:
    src: poetry.bash-completion
    dest: "/etc/bash_completion.d/poetry.bash-completion"
    mode: 0644
    setype: etc_t
    seuser: system_u
