---
- name: "nvm"
  shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

- name: "node"
  shell: >
    . {{ ansible_env.HOME }}/.nvm/nvm.sh && nvm install {{ item }}
  args:
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}"
    creates: "{{ ansible_env.HOME }}/.nvm/versions/{{ item }}"
  loop:
    - node

- name: create npm user package cache directory
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/.npm-global"
    group: "{{ ansible_env.USER }}"
    owner: "{{ ansible_env.USER }}"

- name: copy npmrc
  copy:
    src: "{{ role_path }}/files/npmrc"
    dest: "{{ ansible_env.HOME }}/.npmrc"
    group: "{{ ansible_env.USER }}"
    owner: "{{ ansible_env.USER }}"
