name: "App Release: Android Development"

on:
  repository_dispatch:
    types: android_development_release
    inputs:
      branch:
        description: Branch to release from
        default: "develop"
        required: true
      commit:
        description: commit to release from
        default: ""
        required: false
      workspace:
        description: workspace package to trigger
        default: ""
        required: false

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.commit }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.yarn-cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.node-version }}-

      - name: Yarn Install
        run: yarn install --frozen-lockfile --prefer-offline

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run app workspace setup
        run: yarn workspace ${{ github.event.client_payload.workspace }} setup

      - name: Build App
        run: |
          echo "📦 would have built ${{ github.event.client_payload.workspace }}"
