name: Pull Request Linter

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened

jobs:
  lint:
    name: Lint pull request title
    runs-on: ubuntu-latest
    steps:
      - name: Lint pull request title
        uses: jef/conventional-commits-pr-action@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
